#!/bin/bash
set +x

echo "Build Started.............."

if [ -z "${BRANCH_MENU}" ]
then
echo "${red}Branch name cannot be empty..Exiting ${reset}"
exit 1
fi      
cd /root/artemis/
git stash
git fetch
git checkout ${BRANCH_MENU}
git reset --hard origin/${BRANCH_MENU}
npm install
pm2 restart all
npm run build
